class Template:
    def __init__(
        self,
        text=...,
        filename=...,
        uri=...,
        format_exceptions=...,
        error_handler=...,
        lookup=...,
        output_encoding=...,
        encoding_errors=...,
        module_directory=...,
        cache_args=...,
        cache_impl=...,
        cache_enabled=...,
        cache_type=...,
        cache_dir=...,
        cache_url=...,
        module_filename=...,
        input_encoding=...,
        module_writer=...,
        default_filters=...,
        buffer_filters=...,
        strict_undefined=...,
        imports=...,
        future_imports=...,
        enable_loop=...,
        preprocessor=...,
        lexer_cls=...,
        include_error_handler=...,
    ) -> None: ...
    def render(self, *args: object, **data: object) -> str: ...
