---
runs:
  using: composite
  steps:
    - name: Install nox
      run: pipx install nox
      shell: bash
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-install-version || matrix.python-version }}
    - name: Install libgirepository
      run: sudo apt-get install -y libgirepository1.0-dev
      if: matrix.os == 'ubuntu-latest'
      shell: bash
